substitutions:
  device_name: "mr60abd1-mmwave-sensor"
  device_name_pretty: "mr60abd1-mmwave-sensor"
  ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  uart_tx_pin: GPIO17
  uart_rx_pin: GPIO16

esphome:
  name: r60abd1-espc6-sensor
  friendly_name: R60ABD1-ESPC6-SENSOR
  includes:
    - header/r60abd1_sensor.h
  

esp32:
  board: esp32-c6-devkitm-1
  flash_size: 4MB
  variant: esp32c6
  framework:
    type: esp-idf
    version: "5.3.0"
    platform_version: 6.8.1
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y
      
# Enable logging
logger:
  logs:
    level: DEBUG
  
  

# Enable Home Assistant API
api:
  encryption:
    key: "................."

ota:
  - platform: esphome
    password: "......................."

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: xxx.xxx.xxx.xxx.

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "................"
    password: "............."

captive_portal:
# UART configuration for communication with the sensor
uart:
  id: uart_bus
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 115200

sensor:
  - platform: custom
    lambda: |-
      auto r60_sensor = new R60ABD1Sensor(id(uart_bus));
      App.register_component(r60_sensor);
      return {r60_sensor->presence_sensor,
              r60_sensor->motion_sensor,
              r60_sensor->heartbeat_sensor,
              r60_sensor->respiratory_sensor,
              r60_sensor->sleep_quality_sensor,
              r60_sensor->bed_status_sensor};
    sensors:
      - name: "Presence Sensor"
      - name: "Motion Sensor"
      - name: "Heartbeat Rate"
      - name: "Respiratory Rate"
      - name: "Sleep Quality"
      - name: "Bed Status"
       

